// Generated by CoffeeScript 1.6.3
(function(doc) {
  var result;
  if (doc.message == null) {
    return;
  }
  result = {
    "to": doc.to || "",
    "from": doc.from || "",
    "received": doc.time_received || "",
    "sent": doc.time_sent || "",
    "message": doc.message
  };
  return emit(doc._id, result);
});
