// Generated by CoffeeScript 1.6.3
(function(head, req) {
  var columnNames, csvRow, first, key, oneRow, row, value;
  start({
    "headers": {
      "Content-Type": "text/csv; charset=UTF-8",
      "Content-Disposition": req.query.download === "false" ? "" : "attachment; filename=\"Haiti-" + ((new Date()).getFullYear()) + "-" + ((new Date()).getMonth() + 1) + "-" + ((new Date()).getDate()) + ".csv\""
    }
  });
  first = true;
  while (row = getRow()) {
    oneRow = row.value;
    if (first) {
      columnNames = [];
      for (key in oneRow) {
        value = oneRow[key];
        columnNames.push("\"" + key + "\"");
      }
      send(columnNames.join(",") + "\n");
      first = false;
    }
    csvRow = [];
    for (key in oneRow) {
      value = oneRow[key];
      csvRow.push('"' + String(value).replace(/"/g, '”') + '"');
    }
    send(csvRow.join(",") + "\n");
  }
});
