// Generated by CoffeeScript 1.6.3
var Pomegranate, Router, SendView, _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Router = (function(_super) {
  __extends(Router, _super);

  function Router() {
    _ref = Router.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Router.prototype.routes = {
    "login": "login",
    "send": "send",
    "": "send"
  };

  Router.prototype.send = function() {
    var sendView;
    sendView = new SendView();
    return sendView.render();
  };

  Router.prototype["default"] = function() {
    var landingView;
    return landingView = new LandingView();
  };

  return Router;

})(Backbone.Router);

SendView = (function(_super) {
  __extends(SendView, _super);

  function SendView() {
    _ref1 = SendView.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  SendView.prototype.el = "#send";

  SendView.prototype.events = {
    "click button:contains(Send)": "send",
    "keyup #numbers": "countNumbers",
    "keyup #text": "countCharacters"
  };

  SendView.prototype.render = function() {
    return this.$el.html("        <h2>Numbers to send text/SMS to <span id='number_phone_numbers'></span></h2>        <textarea id='numbers' style='height:200px'></textarea>        <h2>Message to send <span id='chars_left'></span></h2>        <textarea id='text' style=''></textarea>        <br/>        <button>Send</button>      </div>    ");
  };

  SendView.prototype.send = function() {
    var number, numbers, _i, _len, _results;
    numbers = $("#numbers").val().split(/\n/);
    $("#log").append("Adding " + numbers.length + " message(s) to the outgoing message queue<br>");
    _results = [];
    for (_i = 0, _len = numbers.length; _i < _len; _i++) {
      number = numbers[_i];
      _results.push($.couch.db("pomegranate").saveDoc({
        message: $("#text").val(),
        to: number
      }));
    }
    return _results;
  };

  SendView.prototype.countNumbers = function() {
    return $("#number_phone_numbers").text("(" + ($("#numbers").val().split(/\n/).length) + " numbers entered)");
  };

  SendView.prototype.countCharacters = function() {
    return $("#chars_left").text("(Characters left: " + (160 - $("#text").val().length) + ")");
  };

  return SendView;

})(Backbone.View);

Pomegranate = {};

Pomegranate.router = new Router();

Backbone.history.start();

Pomegranate.debug = function(string) {
  console.log(string);
  return $("#log").append(string + "<br/>");
};
